<a href="https://colab.research.google.com/github/Poomrapee25/Lab-5/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 66015xxx ชื่อ :

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที


In [ ]:
def is_leap(year):

    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

def day_of_year(day, month, year):

    days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

    if is_leap(year):
        days_in_month[1] = 29

    day_of_year = sum(days_in_month[:month-1]) + day

    return day_of_year

print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365


Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365


Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ


In [ ]:
def is_leap(year):
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

def days_in_month(month, year):
    days = [31, 28 + (1 if is_leap(year) else 0), 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    return days[month - 1]

def day_of_year(day, month, year):
    return sum(days_in_month(m, year) for m in range(1, month)) + day

def date_diff(date1, date2):
    day1, month1, year1 = map(int, date1.split('-'))
    day2, month2, year2 = map(int, date2.split('-'))

    def total_days(day, month, year):
        return (year - 1) * 365 + (year - 1) // 4 - (year - 1) // 100 + (year - 1) // 400 + day_of_year(day, month, year)

    days1 = total_days(day1, month1, year1)
    days2 = total_days(day2, month2, year2)

    return days2 - days1 + 1

print(date_diff("1-1-2018", "1-1-2020"))
print(date_diff("25-12-1999", "9-3-2000"))
print(date_diff("1-1-2000", "1-1-2001"))
print(date_diff("1-1-2001", "1-1-2002"))
print(date_diff("1-3-2000", "1-3-2001"))
print(date_diff("1-1-2023", "31-12-2023"))



731
76
367
366
366
365


Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1


In [ ]:
def is_leap(year):
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

def days_in_month(month, year):
    if month < 1 or month > 12:
        return -1
    days = [31, 28 + (1 if is_leap(year) else 0), 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    return days[month - 1]

def day_of_year(day, month, year):
    if day < 1 or month < 1 or month > 12 or day > days_in_month(month, year):
        return -1
    return sum(days_in_month(m, year) for m in range(1, month)) + day

def date_diff(date1, date2):
    try:
        day1, month1, year1 = map(int, date1.split('-'))
        day2, month2, year2 = map(int, date2.split('-'))
    except ValueError:
        return -1

    if (day1 < 1 or day1 > days_in_month(month1, year1) or
        day2 < 1 or day2 > days_in_month(month2, year2) or
        month1 < 1 or month1 > 12 or
        month2 < 1 or month2 > 12):
        return -1

    def total_days(day, month, year):
        return (year - 1) * 365 + (year - 1) // 4 - (year - 1) // 100 + (year - 1) // 400 + day_of_year(day, month, year)

    days1 = total_days(day1, month1, year1)
    days2 = total_days(day2, month2, year2)

    if days1 == -1 or days2 == -1:
        return -1

    return days2 - days1 + 1

print(date_diff("1-1-2018", "1-1-2020"))
print(date_diff("25-12-1999", "9-3-2000"))
print(date_diff("1-1-2000", "1-1-2001"))


731
76
367


1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()


In [ ]:
import math

def simulate_fish_population(n, p, months=3, total_years=10):
    total_months = total_years * 12
    fish_population = [n] * 2
    monthly_mortality_rate = p / 100

    results = []

    for current_month in range(1, total_months + 1):
        males = fish_population[0]
        females = fish_population[1]

        if females > 0:
            new_eggs = females * 300
            new_fry = new_eggs // 2
        else:
            new_eggs = 0
            new_fry = 0

        total_fish = males + females
        surviving_fish = total_fish * (1 - monthly_mortality_rate)

        fish_population = [int(surviving_fish // 2), int(surviving_fish // 2)]

        fish_population[0] += new_fry // 2
        fish_population[1] += new_fry // 2

        if current_month % months == 0:
            total_fish_count = fish_population[0] + fish_population[1]
            results.append((current_month, total_fish_count))

    return results

n = 2
p = 10

results = simulate_fish_population(n, p)

for month, population in results:
    print(f"Month {month}: Total fish population = {population}")



Month 3: Total fish population = 1739628
Month 6: Total fish population = 760644471106
Month 9: Total fish population = 332588356117436442
Month 12: Total fish population = 145422755080391077381422
Month 15: Total fish population = 63585442202625280151893253290
Month 18: Total fish population = 27802447133313705744301314562976606
Month 21: Total fish population = 12156494314177928129408406856528620956730
Month 24: Total fish population = 5315372179363504668471604267009933806872502542
Month 27: Total fish population = 2324122454629069515168176195700943874304298921849418
Month 30: Total fish population = 1016212035928943269140243428875487063229896457010141565502
Month 33: Total fish population = 444334118415316010217406408395549841486166761091115303588508378
Month 36: Total fish population = 194283084442547570348367379443944627805701864766323910720803518827246
Month 39: Total fish population = 84949400318679160556400002603732124993292116700465483567278983441740222954
Month 42: Total fish

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน






In [ ]:
def find_mismatch(str1, str2):
    str1 = str1.lower()
    str2 = str2.lower()

    if str1 == str2:
        return 0

    len1, len2 = len(str1), len(str2)

    def is_one_edit_away(s1, s2):
        len1, len2 = len(s1), len(s2)

        if abs(len1 - len2) > 1:
            return False

        if len1 < len2:
            s1, s2 = s2, s1
        i, j = 0, 0
        found_difference = False

        while i < len(s1) and j < len(s2):
            if s1[i] != s2[j]:
                if found_difference:
                    return False
                found_difference = True
                if len1 == len2:
                    j += 1
            else:
                j += 1
            i += 1

        return True

    if is_one_edit_away(str1, str2):
        return 1

    return 2

print(find_mismatch("Python", "Java"))
print(find_mismatch("book", "boot"))
print(find_mismatch("fan", "fun"))
print(find_mismatch("sin", "sink"))
print(find_mismatch("Dog", "dog"))
print(find_mismatch("poke", "spoke"))
print(find_mismatch("poker", "poke"))


2
1
1
1
0
1
1


3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|




In [ ]:
def is_one_edit_away(word1, word2):
    len1, len2 = len(word1), len(word2)

    if abs(len1 - len2) > 1:
        return False

    if len1 > len2:
        word1, word2 = word2, word1
        len1, len2 = len2, len1

    i, j = 0, 0
    found_difference = False

    while i < len1 and j < len2:
        if word1[i] != word2[j]:
            if found_difference:
                return False
            found_difference = True
            if len1 == len2:
                i += 1
        else:
            i += 1
        j += 1

    return True

def spelling_correction(input_string, correct_spells):
    words = input_string.strip().split()

    correct_spells = [spell.lower() for spell in correct_spells]

    output_words = []

    for word in words:
        lower_word = word.lower()

        if len(lower_word) <= 2:
            output_words.append(word)
            continue

        if lower_word in correct_spells:
            output_words.append(word)
        else:
            corrected = None
            for spell in correct_spells:
                if is_one_edit_away(lower_word, spell):
                    corrected = spell
                    break

            if corrected:
                if word.islower():
                    output_words.append(corrected)
                elif word.istitle():
                    output_words.append(corrected.capitalize())
                else:
                    output_words.append(corrected.upper())
            else:
                output_words.append(word)

    return ' '.join(output_words)

print(spelling_correction("Thes is the Firs cas", ['that', 'first', 'case', 'car']))

print(spelling_correction("programming is fan and easy", ['programming', 'this', 'fun', 'easy', 'book']))

print(spelling_correction("Thes is vary essy", ['this', 'is', 'very', 'easy']))

print(spelling_correction("Wee ipve Pythen", ['we', 'live', 'ln', 'Python']))


Thes is the First case
programming is fun and easy
This is very easy
We ipve Python


4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]


In [ ]:
def find_word_horizontal(crosswords, word):
    num_rows = len(crosswords)

    for row_index, row in enumerate(crosswords):
        horizontal_string = ''.join(row)

        if word in horizontal_string:
            start_index = horizontal_string.index(word)
            return [row_index, start_index]

    return None

crosswords = [['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t','e','t','k']]
word = 'cat'

print(find_word_horizontal(crosswords, word))


[2, 1]


5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]


In [ ]:
def find_word_vertical(crosswords, word):
    num_rows = len(crosswords)
    if num_rows == 0:
        return None
    num_cols = len(crosswords[0])
    for col in range(num_cols):
        vertical_string = ''.join(crosswords[row][col] for row in range(num_rows))

        if word in vertical_string:
            start_index = vertical_string.index(word)
            return [start_index, col]
    return None
crosswords = [['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t','e','t','k']]
word = 'cat'
print(find_word_vertical(crosswords, word))


[1, 0]


6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```




In [ ]:
def capitalize_word_in_crossword(crosswords, word):
    rows = len(crosswords)
    cols = len(crosswords[0]) if rows > 0 else 0
    word_len = len(word)

    def capitalize_in_list(lst, word):
        for i in range(len(lst) - word_len + 1):
            if lst[i:i + word_len] == list(word):
                for j in range(word_len):
                    lst[i + j] = lst[i + j].upper()
                return True
        return False

    for row in crosswords:
        capitalize_in_list(row, word)

    for col in range(cols):
        col_list = [crosswords[row][col] for row in range(rows)]
        if capitalize_in_list(col_list, word):
            for row in range(rows):
                crosswords[row][col] = col_list[row]

    return crosswords

crosswords1 = [['s','d','o','g'],
               ['c','u','c','m'],
               ['a','x','a','t'],
               ['t','e','t','k']]
word1 = 'cat'
print(capitalize_word_in_crossword(crosswords1, word1))

crosswords2 = [['s','d','o','g'],
               ['c','u','c','m'],
               ['a','c','a','t'],
               ['t','e','t','k']]
word2 = 'cat'
print(capitalize_word_in_crossword(crosswords2, word2))

[['s', 'd', 'o', 'g'], ['C', 'u', 'C', 'm'], ['A', 'x', 'A', 't'], ['T', 'e', 'T', 'k']]
[['s', 'd', 'o', 'g'], ['C', 'u', 'c', 'm'], ['A', 'C', 'A', 'T'], ['T', 'e', 't', 'k']]
